# -*- coding: utf-8 -*-
"""Colab & Conquer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fz64DQ_TODGavjca2GBGyse2Tc81UhKs
"""

# Step 1: Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt

# Step 2: Load the dataset directly from the URL
url = 'https://bit.ly/4nejNue'
df = pd.read_csv(url)

# Step 3: Display the first few rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# Step 4: Show basic statistical information
print("\n Dataset Description (.describe()):")
print(df.describe())
# Step 5: Show mean, median, and standard deviation of numeric columns
print("\n Mean of each column:")
print(df.mean(numeric_only=True))

print("\n Median of each column:")
print(df.median(numeric_only=True))

print("\n Standard Deviation of each column:")
print(df.std(numeric_only=True))

# Step 6: Plot histograms of all numerical features
print("\n Generating histograms...")
df.hist(figsize=(10, 10), bins=20, edgecolor='black')
plt.suptitle("Histograms of All Numerical Features", fontsize=16)
plt.tight_layout()
plt.show()